# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Randall Koutnik
email: blog@rkoutnik.com
description: > # this means to ignore newlines until "baseurl:"
  You've found my corner of the internet!
  I opine on various topics that interest me (mostly tech, startups & the like).
  Stick around and enjoy yourself!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rkoutnik.com" # the base hostname & protocol for your site
# url: "http://localhost:4000"
twitter_username: rkoutnik
github_username:  SomeKittens

# Build settings
markdown: kramdown

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,PUT,POST,DELETE,OPTIONS"

collections:
  talks:
    output: true
    permalink: /talks/:path/